openapi: 3.0.1
info:
  title: Short Ciphers API
    
  description: |-
    Provides Short Cipher Information
  version: 1.0.0

  contact:
    name: dev
    email: dev@example.com
    
servers:
  - url: 'http://locahost:8000'
    description: DEV
  - url: ''
    description: SIT
  - url: ''
    description: PreProd
  - url: ''
    description: PROD
    
paths:
  /cem/bff/api/v1/shortcipher:
    post:
      summary: add Short Cipher
      operationId: add-cem-bff-shortciphers-v1-shortcipher
      responses:
        '200':
          $ref: '#/components/responses/200-CEM-AddShortCipherResponse'
        '400':
          $ref: '#/components/responses/CEM400-Error-Response'
        '401':
          $ref: '#/components/responses/CEM401-Error-Response'
        '403':
          $ref: '#/components/responses/CEM403-Error-Response'
        '404':
          $ref: '#/components/responses/CEM404-Error-Response'
        '405':
          $ref: '#/components/responses/CEM405-Error-Response'
        '409':
          $ref: '#/components/responses/409-Error-Response'
        '500':
          $ref: '#/components/responses/CEM500-Error-Response'
      description: "**Summary:**\n\n\t This API requests for adding a new Short Cipher in B2BPortal for the given account number {MSISDN / Service Account Number}. \n\n  * **Data Power API URLs:** \n \t\t \t\t <table><tr><td>**Production:**</td><td></td></tr><tr><td> **UAT:**</td><td> </td></tr><tr><td> **Pre-production:**</td><td></td></tr><tr><td> **SIT:**</td><td></td></tr><tr><td> **Development:**</td><td></td></tr></table> \n \t\t \t\t \n * **DB Tables:**\n\n\t\t Not Applicable  \n\n**Supported Authentications:**\n   * Full Login\n   * Quick Login"
      parameters:
        - $ref: '#/components/parameters/X-Correlation-Id'
        - $ref: '#/components/parameters/X-Source-Channel'
        - $ref: '#/components/parameters/X-Commercial-Id'
        - $ref: '#/components/parameters/X-Cem-Key'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CEM-AddShortCipherRequest'
            examples:
              Add Short Cipher Request with Service Number:
                value:
                  version: v1
                  journey: SHORTCIPHERS
                  operation: ADD_SHORT_CIPHER
                  language: en
                  shortCipher:
                    cipher: 34567
                    cNumber: 5667890
        description: ''
        
      tags:
        - Short Cipher Services
components:
  schemas:
    ErrorResponse:
      properties:
        status:
          $ref: '#/components/schemas/Status'
      description: Error Response Model
    Status:
      type: object
      description: Model Represents Status
      properties:
        code:
          type: string
          description: Possible status code / error codes <ul><li>MAPI-400 - Invalid input</li><li>MAPI-400_1 - Missing Request header</li><li>MAPI-400_2 - Missing request parameters</li><li>MAPI-400_3 - Missing path parameter</li><li>MAPI-400_4 - Invalid Request</li><li>MAPI-401 - Not authenticated</li><li>MAPI-403 - Not authorized</li><li>MAPI-403_1 - Not authorized</li><li>MAPI-404 - Resource Not found</li><li>MAPI-405 - Method Not Supported</li><li>MAPI-409 - Resource State Conflict</li><li>MAPI-500 - Generic error</li><li>MAPI-502 - Generic error</li><li>MAPI-504 - Generic error</li><li>MAPI-000 - success</li><li>MBE_300 - General Error</li><li>MBE_323 - Not Authorized</li><li>MBE_485 - Requested URI Not Found</li><li>401 - Missing Authorization</li><li>MAPI-404 - API not found</li><li>MAPI-300 - Missing Request header</li><li>MAPI-301 - Missing request parameters</li><li>MAPI-302 - Invalid HTTP Method</li><li>MAPI-303 - Missing path parameter</li><li>MAPI-304 - Invalid input</li><li>MAPI-305 - Invalid Request</li><li>MAPI-9999 - Data not found</li><li>MAPI-9998 - Backend Error</li><li>MAPI-9017 - Invalid amount</li></ul>
          enum:
            - MAPI-400
            - MAPI-400_1
            - MAPI-400_2
            - MAPI-400_3
            - MAPI-400_4
            - MAPI-401
            - MAPI-403
            - MAPI-403_1
            - MAPI-404
            - MAPI-405
            - MAPI-409
            - MAPI-500
            - MAPI-502
            - MAPI-504
            - MAPI-000
            - MBE_300
            - MBE_323
            - MBE_485
            - MAPI-300
            - MAPI-301
            - MAPI-302
            - MAPI-303
            - MAPI-304
            - MAPI-305
            - MAPI-9999
            - MAPI-9998
            - MAPI-9017
            - '401'
            - MAPI-8008
            - MAPI-8009
            - MAPI-8010
            - MAPI-8011
            - MAPI-8012
            - MAPI-8013
            - MAPI-8014
            - MAPI-8015
            - MAPI-8016
            - MAPI-8017
            - MAPI-8018
            - MAPI-8031
          example: MAPI-400
        message:
          type: string
          description: title of error message
          example: Invalid input
        arabicDetail:
          type: string
          description: details of error message in Arabic
          example: بيانات إدخال غير صالحة لـ
        englishDetail:
          type: string
          description: details of error message in English
          example: Invalid input data for
        help:
          type: string
          description: help for consumer
          example: for more information please check API docs
    ApplicationResponse:
      type: object
      title: ApplicationResponse
      description: Class representing the result of calling a rest web service
      x-examples: {}
      properties:
        status:
          $ref: '#/components/schemas/ResponseStatus'
        data:
          type: object
          description: To hold any object returned as a result of a web service call
          nullable: true
    ResponseStatus:
      type: object
      title: ResponseStatus
      properties:
        statusCode:
          type: string
          description: |-
            * MBE_000: Operation completed successfully
            * MBE_300: The service is currently not available, please try again later
            * MBE_323: Sorry, you are not authorized
            * MBE_347: Resource not found
            * MBE_507: Required field/s is/are missing
            * MBE_508: Unfortunately, you are not eligible for this service.
            * MBE_509: Your number can't be verified, please try again
            * MBE_510: Your verification code is expired, please try again
            * MBE_511: You have reached the allowed number of wrong verification code attempts, please try again
            * MBE_512: Only Physical SIM allowed to activate using OTP service
            * MBE_513: Please enter a valid order id to know the status
            * MBE_514: You attempt your Verification too many times for today
            * MBE_515: Sorry, You are not eligible to this service, refer to figma for the more information
            * MBE_516: Something went wrong when verifying your account, Please try again
            * MBE_519: Coupon does not exist
            * MBE_527: Looks like you already have an e50 plan!
            * MBE_531: Sorry, we could not complete your request to migrate your package as you already have a master line under your ID.
            * MBE_532: Sorry, we could not complete your request to migrate your package as you've reached the maximum number of supplementary lines.
            * MBE_533: Sorry, we could not complete your request to activate a supplementary line as you haven't activated the main line under your ID.
            * NC_101: Data validation error
          enum:
            - MBE_000
            - MBE_300
            - MBE_323
            - MBE_347
            - MBE_507
            - MBE_508
            - MBE_509
            - MBE_510
            - MBE_511
            - MBE_512
            - MBE_513
            - MBE_514
            - MBE_515
            - MBE_516
            - MBE_519
            - MBE_527
            - MBE_531
            - MBE_532
            - MBE_533
            - NC_101
            - MBE_500
        statusMessage:
          type: string
          description: Message summarizing the result of calling the web service result
        errors:
          type: array
          description: return list of errors (if any)
          items:
            type: string
    StatusCEM:
      type: object
      description: Model Represents Status Response of new CEM standard
      properties:
        Code:
          type: string
          description: Possible error codes
          example: MAPI-400
        SourceCode:
          type: string
          description: 'Error code repreents the gateway status. MAPI-000 means success, remaining are error.'
        SourceMessage:
          type: string
          description: Error description like success or Error.
          example: Success
        MessageAr:
          type: string
          description: Presentable error description in Arabic
          example: نجاح
        MessageEn:
          type: string
          description: Presentable error description in English
          example: Success
        Help:
          type: string
          description: Help URL or message if any
          example: For more information please check API docs
    CEM-AddShortCipherRequest:
      title: CEM-AddShortCipherRequest
      type: object
      properties:
        version:
          type: string
          example: v1
          default: v1
          description: This specifies which version of configuration to be used.
        journey:
          type: string
          example: Add Short Cipher
          description: ' This defines the JOURNEY of the use case.'
        operation:
          type: string
          example: ADD_SHORTCIPHER
          description: This defines the operation flow of use case.
        language:
          type: string
          example: en
          default: en
          description: Specifies the prefered language by caller
        cipher:
          type: string
          example: 345678
          description: Short Cipher for a given service number
        cNumber: 
          type: string
          example: 560510521
          description: service number
      required:
        - version
        - journey
        - operation
        - cipher
        - cNumber
      description: 'Model represents Adding a new Short Cipher. Here the cNumber represents user selected service number and cipher represents the Short Cipher'
   
    AddShortCipherResponse:
      title: AddShortCipherResponse
      type: object
      properties:
        status:
          type: string
          description: Status of adding Short Cipher
          example: "SUCCESS"
       
    CEM-AddShortCipherResponse:
      title: CEM-AddShortCipherResponse
      type: object
      description: CEM Add Short Cipher response
      properties:
        status:
          $ref: '#/components/schemas/StatusCEM'
        data:
          $ref: '#/components/schemas/AddShortCipherResponse'
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
  parameters:
    X-Correlation-Id:
      name: x-Correlation-Id
      in: header
      required: true
      schema:
        type: string
      description: Correlation ID of the (Correlation ID for the ongoing journey, in case of direct/single API call without journey, correlation and transaction ID can share the same value)
    X-Source-Channel:
      name: x-Source-Channel
      in: header
      required: true
      schema:
        type: string
        maxLength: 30
        minLength: 1
        example: Portal
      description: Mandatory attribute to identify the caller. Value has to be enriched by Apigee based on cem-key. Should not be provided by caller.
    X-Commercial-Id:
      name: x-Commercial-Id
      required: true
      in: header
      schema:
        type: string
        maxLength: 30
        minLength: 10
        example: 720755841
      description: 'Mandatory attribute to uniquely identify the API call, in case of direct/single API call without journey, correlation and transaction id can share same value.'
    X-Cem-Key:
      name: X-Cem-Key
      in: header
      required: true
      schema:
        type: string
      description: 'Channel Engagement Manager Key'
    channel:
      name: channel
      in: header
      required: true
      schema:
        type: string
        enum:
          - B2B-ANDROID
          - B2B-IOS
          - PORTAL
        example: B2B-ANDROID
      description: Requester  Channel
    referenceId:
      name: referenceId
      in: header
      required: true
      schema:
        type: string
        maxLength: 30
        minLength: 10
        example: 3ec16808-0f0f-4e7b-b22e-1817d7ee2342
      description: Unique reference id for each request
    User_id:
      name: User_id
      in: header
      required: true
      schema:
        type: string
      description: User_id of current user
  headers:
    X-Correlation-Id:
      required: true
      schema:
        type: string
        maxLength: 30
        minLength: 10
        example: 3ec16808-0f0f-4e7b-b22e-1817d7ee2342
      description: It is used for distributed tracing to correlate the related MS services calls and backend API calls (if possible) to make it easy for troubleshooting.
    X-Source-Channel:
      required: true
      schema:
        type: string
        maxLength: 30
        minLength: 1
        example: WEB
      description: Mandatory attribute to identify the caller
    X-Commercial-Id:
      required: true
      schema:
        type: string
        maxLength: 30
        minLength: 10
        example: 720755841
      description: 'Mandatory attribute to uniquely identify the API call, in case of direct/single API call without journey, correlation and transaction id can share same value.'
    X-Cem-Key:
      required: true
      schema:
        type: string
        maxLength: 30
        minLength: 10
        example: sr_123hg87asfafF32
      description: GUID reference for every response of the API consumer
  responses:
    '400':
      description: Data validation error/s
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApplicationResponse'
          examples:
            Data Validation Error:
              value:
                status:
                  statusCode: NC_101
                  statusMessage: Data validation error
                  errors:
                    - Trasnaction id not found
                data: null
    CEM400-Error-Response:
      description: Bad Request. The server did not understand the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCEM'
          examples:
            Invalid input data:
              $ref: '#/components/examples/MAPI-400-CEM'
            Missing Request header:
              $ref: '#/components/examples/MAPI-400_1-CEM'
            Missing Request parameter:
              $ref: '#/components/examples/MAPI-400_2-CEM'
            Missing Path Parameter:
              $ref: '#/components/examples/MAPI-400_3-CEM'
            Invalid Request:
              $ref: '#/components/examples/MAPI-400_4-CEM'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
          
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    CEM401-Error-Response:
      description: 'Unauthorized, it lacks valid authentication for the requested resource.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCEM'
          examples:
            Not authenticated:
              $ref: '#/components/examples/MAPI-401-CEM'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    CEM403-Error-Response:
      description: Forbidden. Access is forbidden to the requested resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCEM'
          examples:
            Not authorized:
              $ref: '#/components/examples/MAPI-403-CEM'
            Login Type is unauthorized:
              $ref: '#/components/examples/MAPI-403_1-CEM'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
          
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    CEM405-Error-Response:
      description: Method Not allowed. The HTTP method specified in the request is not allowed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCEM'
          examples:
            Invalid HTTP Method:
              $ref: '#/components/examples/MAPI-405-CEM'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
          
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    CEM500-Error-Response:
      description: Internal Server Error. The request was not completed. The server encountered an unexpected condition.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCEM'
          examples:
            Generic Exception:
              $ref: '#/components/examples/MAPI-500-CEM'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
          
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    CEM502-Error-Response:
      description: BAD GATEWAY. The request was not completed. The server received an invalid response from the upstream server.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCEM'
          examples:
            Backend Generic Exception:
              $ref: '#/components/examples/MAPI-502-CEM'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    CEM504-Error-Response:
      description: Gateway Timeout. The gateway has timed out.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCEM'
          examples:
            GATEWAY TIMEOUT:
              $ref: '#/components/examples/MAPI-504-CEM'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
          
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    400-Error-Response:
      description: Bad Request. The server did not understand the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Invalid input data:
              $ref: '#/components/examples/MAPI-400'
            Missing Request header:
              $ref: '#/components/examples/MAPI-400_1'
            Missing Request parameter:
              $ref: '#/components/examples/MAPI-400_2'
            Missing Path Parameter:
              $ref: '#/components/examples/MAPI-400_3'
            Invalid Authorization Code / MSISDN is not available:
              $ref: '#/components/examples/MAPI-400_4'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
          
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    401-Error-Response:
      description: Unauthorized. Indicates that the request has not been applied because it lacks valid authentication for the requested resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Not authenticated:
              $ref: '#/components/examples/MAPI-401'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
          
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    403-Error-Response:
      description: Forbidden. Access is forbidden to the requested resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Not authorized:
              $ref: '#/components/examples/MAPI-403'
            Login Type is unauthorized:
              $ref: '#/components/examples/MAPI-403_1'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
          
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    404-Error-Response:
      description: Not Found. The server can not find the requested resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Requested Resource Not found:
              $ref: '#/components/examples/MAPI-404'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
          
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    405-Error-Response:
      description: Method Not allowed. The HTTP method specified in the request is not allowed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Invalid HTTP Method:
              $ref: '#/components/examples/MAPI-405'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
          
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    409-Error-Response:
      description: Conflict. The request could not be completed because of a conflict.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Request resource conflict with current state:
              $ref: '#/components/examples/MAPI-409'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    500-Error-Response:
      description: Internal Server Error. The request was not completed. The server met an unexpected condition.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Generic Exception:
              $ref: '#/components/examples/MAPI-500'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    502-Error-Response:
      description: BAD GATEWAY. The request was not completed. The server received an invalid response from the upstream server.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Backend Generic Exception:
              $ref: '#/components/examples/MAPI-502'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    504-Error-Response:
      description: Gateway Timeout. The gateway has timed out.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            GATEWAY TIMEOUT:
              $ref: '#/components/examples/MAPI-504'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    default-Error-Response:
      description: Unexpected error. The request was not completed. The server met an unexpected condition.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Default Error:
              $ref: '#/components/examples/MAPI-500'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    CEM404-Error-Response:
      description: Error response in case of requested resource is not available.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusCEM'
          examples:
            Request Resource Not Found:
              $ref: '#/components/examples/MAPI-404-CEM'
      headers:
        X-Correlation-Id:
          $ref: '#/components/headers/X-Correlation-Id'
        X-Source-Channel:
          $ref: '#/components/headers/X-Source-Channel'
        X-Commercial-Id:
          $ref: '#/components/headers/X-Commercial-Id'          
        X-Cem-Key:
          $ref: '#/components/headers/X-Cem-Key'
    200-CEM-AddShortCiperResponse:
      description: AddShort Cipher Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CEM-AddShortCipherResponse'
          examples:
           Add Short Cipher success response:
              $ref: '#/components/examples/AddShortCipherSuccessResponse'
   
  examples:
    '401':
      value:
        StatusCode: '401'
        StatusMessage: invalid Token
    ErrorResponse_400:
      value:
        code: MAPI-400
        description: Invalid input
        retry: 'N'
        messageAr: بيانات إدخال غير صالحة لـ
        messageEn: Invalid input data for
    MAPI-400-CEM:
      description: Error response in case of invalid request input.
      value:
        status:
          code: '400'
          sourceCode: MAPI-400
          sourceMessage: Invalid input
          messageAr: بيانات إدخال غير صالحة لـ
          messageEn: Invalid input data for
          help: For more information please check API docs
    MAPI-400_1-CEM:
      description: Error response in case of missing mandatory request headers.
      value:
        status:
          code: '400'
          sourceCode: MAPI-400_1
          sourceMessage: Missing Request header
          messageAr: رأس الطلب الإلزامي مفقود
          messageEn: Missing mandatory Request header
          help: For more information please check API docs
    MAPI-400_2-CEM:
      description: Error response in case of missing mandatory request parameters.
      value:
        status:
          code: '400'
          sourceCode: MAPI-400_2
          sourceMessage: Missing Request parameter
          messageAr: معلمة الطلب الإلزامية مفقودة
          messageEn: Missing mandatory Request Parameter
          help: For more information please check API docs
    MAPI-400_3-CEM:
      description: Error response in case of any mandatory path variables are missed.
      value:
        status:
          code: '400'
          sourceCode: MAPI-400_3
          sourceMessage: Missing Path Parameter
          messageAr: 'متغير المسار الإلزامي مفقود:'
          messageEn: 'Missing Mandatory Path Variable:'
          help: For more information please check API docs
    MAPI-400_4-CEM:
      description: Error response in case of invalid authorization code.
      value:
        status:
          code: '400'
          sourceCode: MAPI-400_4
          sourceMessage: Invalid Request
          messageAr: Invalid Authorization Code / MSISDN is not available
          messageEn: Invalid Authorization Code / MSISDN is not available
          help: For more information please check API docs
    MAPI-401-CEM:
      description: Error response in case of user is not authenticated
      value:
        status:
          code: '401'
          sourceCode: MAPI-401
          sourceMessage: Not authenticated
          messageAr: آسف ، أنت غير مصرح لك
          messageEn: 'Sorry, you are not authenticated'
          help: For more information please check API docs
    MAPI-403-CEM:
      description: Error response in case of user token is not allowed to use the service.
      value:
        status:
          code: '403'
          sourceCode: MAPI-403
          sourceMessage: Not authorized
          messageAr: آسف ، أنت غير مصرح لك
          messageEn: 'Sorry, you are not authorized to requested resource'
          help: For more information please check API docs
    MAPI-403_1-CEM:
      description: Error response in case of login type is not allowed to use the service.
      value:
        status:
          code: '403'
          sourceCode: MAPI-403_1
          sourceMessage: Not authorized
          messageAr: عذرًا ، نوع تسجيل الدخول غير مصرح به لاستخدام هذه الخدمة
          messageEn: 'Sorry, Login Type is unauthorized for using this service'
          help: For more information please check API docs
    MAPI-404-CEM:
      description: Error response in case of requested resource is not available.
      value:
        status:
          code: '404'
          sourceCode: MAPI-404
          sourceMessage: Resource Not found API URL
          messageAr: عذرا ، لم يتم العثور على المورد المطلوب
          messageEn: 'Sorry, requested resource Not Found'
          help: For more information please check API docs
    MAPI-405-CEM:
      description: Error response in case of Method not allowed.
      value:
        status:
          code: '405'
          sourceCode: MAPI-405
          sourceMessage: Method Not Supported
          messageAr: عذرا ، طريقة الطلب غير مدعومة
          messageEn: 'Sorry, unsupported Request method'
          help: For more information please check API docs
    MAPI-409-CEM:
      description: Error response in case of conflict of resources.
      value:
        status:
          code: '409'
          sourceCode: MAPI-409
          sourceMessage: Resource State Conflict
          messageAr: طلب يتعارض مع الوضع الحالي
          messageEn: A request conflict with current state ...
          help: For more information please check API docs
    MAPI-500-CEM:
      description: Generic error response in case of error from backend/API.
      value:
        status:
          code: '500'
          sourceCode: MAPI-500
          sourceMessage: Generic error
          messageAr: خطأ غير متوقع ، حاول مرة أخرى.
          messageEn: 'Unexpected error, try again.'
          help: For more information please check API docs
    MAPI-502-CEM:
      description: Generic error response in case of generic error from backend/API.
      value:
        status:
          code: '500'
          sourceCode: MAPI-502
          sourceMessage: Generic error
          messageAr: خطأ غير متوقع ، حاول مرة أخرى.
          messageEn: 'Unexpected error, try again.'
          help: For more information please check API docs
    MAPI-504-CEM:
      description: Generic error response in case of backend/API timeout.
      value:
        status:
          code: '500'
          sourceCode: MAPI-504
          sourceMessage: Generic error
          messageAr: خطأ غير متوقع ، حاول مرة أخرى.
          messageEn: 'Unexpected error, try again.'
          help: For more information please check API docs
    ErrorResponse_400_1:
      value:
        code: MAPI-400_1
        description: Missing Request header
        retry: 'N'
        messageAr: رأس الطلب الإلزامي مفقودة
        messageEn: Missing mandatory Request header
    ErrorResponse_400_2:
      value:
        code: MAPI-400_2
        description: Missing Request parameter
        retry: 'N'
        messageAr: متغير الطلب الإلزامية مفقودة
        messageEn: Missing mandatory Request Parameter
    ErrorResponse_400_3:
      value:
        code: MAPI-400_3
        description: Missing Path Parameter
        retry: 'N'
        messageAr: 'متغير المسار الإلزامي مفقود: '
        messageEn: 'Missing Mandatory Path Variable:'
    ErrorResponse_401:
      value:
        code: MAPI-401
        description: Not authenticated
        retry: 'N'
        messageAr: آسف ، أنت غير مصرح لك
        messageEn: 'Sorry, you are not authenticated'
    ErrorResponse_403:
      value:
        code: MAPI-403
        description: Not authorized
        retry: 'N'
        messageAr: آسف ، أنت غير مصرح لك
        messageEn: 'Sorry, you are not authorized to requested resource'
    ErrorResponse_403_1:
      value:
        code: MAPI-403_1
        description: Not authorized
        retry: 'N'
        messageAr: عذرًا ، نوع تسجيل الدخول غير مصرح به لاستخدام هذه الخدمة
        messageEn: 'Sorry, Login Type is unauthorized for using this service'
    ErrorResponse_404:
      value:
        code: MAPI-404
        description: Resource Not found API URL
        retry: 'N'
        messageAr: عذرا ، لم يتم العثور على المورد المطلوب
        messageEn: 'Sorry, requested resource Not Found'
    ErrorResponse_405:
      value:
        code: MAPI-405
        description: Method Not Supported
        retry: 'N'
        messageAr: عذرا ، طريقة الطلب غير مدعومة
        messageEn: 'Sorry, unsupported Request method'
    ErrorResponse_500:
      value:
        code: MAPI-500
        description: Generic error
        retry: 'N'
        messageAr: 'عفوا, حدث خطأ تقنى'
        messageEn: 'Unexpected error, try again.'
    MAPI-9009:
      description: Error response in case of there is no information found.
      value:
        status:
          code: MAPI-9009
          message: No data found
          arabicDetail: عذرا، لم يتم العثور على بيانات
          englishDetail: 'Sorry, No data found'
          help: For more information please check API docs.
    MAPI-400:
      description: Error response in case of invalid request input.
      value:
        status:
          code: MAPI-400
          message: Invalid input
          arabicDetail: بيانات إدخال غير صالحة لـ
          englishDetail: Invalid input data for
          help: for more information please check API docs
    MAPI-400_1:
      description: Error response in case of missing mandatory request headers.
      value:
        status:
          code: MAPI-400_1
          message: Missing Request header
          arabicDetail: رأس الطلب الإلزامي مفقودالحة
          englishDetail: Missing mandatory Request header
          help: for more information please check API docs
    MAPI-400_2:
      description: Error response in case of missing mandatory request parameters.
      value:
        status:
          code: MAPI-400_2
          message: Missing Request parameter
          arabicDetail: معلمة الطلب الإلزامية مفقودة
          englishDetail: Missing mandatory Request Parameter
          help: for more information please check API docs
    MAPI-400_3:
      description: Error response in case of any mandatory path variables are missed.
      value:
        status:
          code: MAPI-400_3
          message: Missing Path Parameter
          arabicDetail: 'متغير المسار الإلزامي مفقود: '
          englishDetail: 'Missing Mandatory Path Variable:'
          help: for more information please check API docs
    MAPI-400_4:
      description: Error response in case of invalid authorization code.
      value:
        status:
          code: MAPI-400_4
          message: Invalid Request
          arabicDetail: Invalid Authorization Code / MSISDN is not available
          englishDetail: Invalid Authorization Code / MSISDN is not available
          help: for more information please check API docs
    MAPI-401:
      description: Error response in case of user is not authenticated
      value:
        status:
          code: MAPI-401
          message: Not authenticated
          arabicDetail: آسف ، أنت غير مصرح لك
          englishDetail: 'Sorry, you are not authenticated'
          help: for more information please check API docs
    MAPI-403:
      description: Error response in case of user token is not allowed to use the service.
      value:
        status:
          code: MAPI-403
          message: Not authorized
          arabicDetail: آسف ، أنت غير مصرح لك
          englishDetail: 'Sorry, you are not authorized to requested resource'
          help: for more information please check API docs
    MAPI-403_1:
      description: Error response in case of login type is not allowed to use the service.
      value:
        status:
          code: MAPI-403_1
          message: Not authorized
          arabicDetail: عذرًا ، نوع تسجيل الدخول غير مصرح به لاستخدام هذه الخدمة
          englishDetail: 'Sorry, Login Type is unauthorized for using this service'
          help: for more information please check API docs
    MAPI-404:
      description: Error response in case of requested resource is not available.
      value:
        status:
          code: MAPI-404
          message: Resource Not found API URL
          arabicDetail: عذرا ، لم يتم العثور على المورد المطلوب
          englishDetail: 'Sorry, requested resource Not Found'
          help: for more information please check API docs
    MAPI-405:
      description: Error response in case of Method not allowed.
      value:
        status:
          code: MAPI-405
          message: Method Not Supported
          arabicDetail: عذرا ، طريقة الطلب غير مدعومة
          englishDetail: 'Sorry, unsupported Request method'
          help: for more information please check API docs
    MAPI-409:
      description: Error response in case of conflict of resources.
      value:
        status:
          code: MAPI-409
          message: Resource State Conflict
          arabicDetail: طلب يتعارض مع الوضع الحاليوىل
          englishDetail: A request conflict with current state ...
          help: for more information please check API docs
    MAPI-500:
      description: Generic error response in case of error from API.
      value:
        status:
          code: MAPI-500
          message: Generic error
          arabicDetail: 'عفوا, حدث خطأ تقنى'
          englishDetail: 'Unexpected error, try again.'
          help: for more information please check API docs
    MAPI-502:
      description: Generic error response in case of generic error from backend.
      value:
        status:
          code: MAPI-502
          message: Generic Error
          arabicDetail: خطأ غير متوقع ، حاول مرة أخرى.
          englishDetail: 'Unexpected error, try again.'
          help: For more information please check API docs
    MAPI-504:
      description: Generic error response in case of backend timeout.
      value:
        status:
          code: MAPI-504
          message: Generic Error
          arabicDetail: خطأ غير متوقع ، حاول مرة أخرى.
          englishDetail: 'Unexpected error, try again.'
          help: For more information please check API docs
    AddShortCipherResponse:
      description: Add Short Cipher Response
      value:
        data:
            status: 'SUCCESS'
    BackendError:
      value:
        status:
          code: MAPI-9998
          message: Backend Error
          arabicDetail: آسف ، خطأ الخلفية حاول مرة أخرى في وقت لاحق.
          englishDetail: 'Sorry, Backend error try again later.'
          help: for more information please check API docs
        requestInfo:
          referenceId: 3ec16808-0f0f-4e7b-b22e-1817d7ee2342
          consumedTime: 3
    GenericError:
      value:
        status:
          code: MAPI-500
          message: Generic error
          arabicDetail: خطأ غير متوقع ، حاول مرة أخرى.
          englishDetail: 'Unexpected error, try again.'
          help: for more information please check API docs
        requestInfo:
          referenceId: 3ec16808-0f0f-4e7b-b22e-1817d7ee2342
          consumedTime: 3
   
    AddShortCipherSuccessResponse:
      value:
        status:
          code: '200'
          sourceCode: MAPI-000
          sourceMessage: Success
          messageAr: نجاح
          messageEn: Success
          help: For more information please check API docs
        data:
          status: 'SUCCESS'
security:
  - Authorization: []